let shopItemsData = [{
        id: "jfhgbvnscs",
        name: "Cake",
        price: 230,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/pizza.jpg",
    },
    {
        id: "ioytrhndcv",
        name: "Lorem",
        price: 240,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/Hot_dog.jpg",
    },
    {
        id: "wuefbncxbsn",
        name: "Lorem",
        price: 140,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/pizza.jpg",
    },
    {
        id: "thyfhcbcv",
        name: "Lorem",
        price: 240,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/Hot_dog.jpg",
    },
    {
        id: "thiecbawdjksadjk",
        name: "Lorem",
        price: 5850,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/ice_cream.jpg"

    },
    {
        id: "iuertrywebncdjksadjk",
        name: "Lorem",
        price: 4000,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/gallary_6.jpg",
    },
    {
        id: "thierytbvcbvzdhadjk",
        name: "Lorem",
        price: 4500,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/biryani.webp",
    },
    {
        id: "trfoiwfcnbcawdjksadjk",
        name: "Lorem",
        price: 5200,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/buger.jpg",
    },
    {
        id: "cbvxbcvsceldk",
        name: "Lorem",
        price: 3600,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/gallary_2.jpg",
    },
    {
        id: "oiopijmjkhuihb",
        name: "Lorem",
        price: 2100,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/gallary_3.jpg",
    },
    {
        id: "oiopijewyiohbjhib",
        name: "Lorem",
        price: 3200,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/gallary_1.jpg",
    },
    {
        id: "rtytytuyuytyytbvncv",
        name: "Lorem",
        price: 3500,
        desc: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Commodi sint eveniet laboriosam ",
        img: "image/juse.jpg",
    },
];